### ISSUE TITLE
Name conflicts?

### ISSUE THREAD

**Issue by lbc546** [442-location-alarm/location-alarm#5]
On my screen, the app icon shows the name Saved Alarms. However, in my setting of permission, the app is actually named as location alarm

**Comment by lbc546** [comment]
![37307808979783734](https://user-images.githubusercontent.com/35054386/59234449-a2de8b80-8ba1-11e9-88be-42488ce943bd.jpg)
![205266252515719401](https://user-images.githubusercontent.com/35054386/59234452-a540e580-8ba1-11e9-8d9e-9696400b3582.jpg)

**Comment by jamesbmc** [comment]
Fixed - https://github.com/442-location-alarm/location-alarm/commit/6d8fdf38cbb4033f8393fff0181fd12caa5b1788
